"""Fix relationships between User and Message models

Revision ID: f97babbb604c
Revises: 
Create Date: 2024-06-10 13:29:17.601480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f97babbb604c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_message_sender_id', 'user', ['sender_id'], ['id'])
        batch_op.create_foreign_key('fk_message_recipient_id', 'user', ['recipient_id'], ['id'])

    with op.batch_alter_table('photo', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.Text(),
               nullable=False)
        batch_op.alter_column('keywords',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=120),
               nullable=False)
        batch_op.alter_column('filename',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DATETIME(), nullable=True))
        batch_op.alter_column('filename',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.alter_column('keywords',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=200),
               nullable=True)

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_constraint('fk_message_sender_id', type_='foreignkey')
        batch_op.drop_constraint('fk_message_recipient_id', type_='foreignkey')

    # ### end Alembic commands ###
